name: build & release

on:
  push:
    tags:
      - 'v\d+.\d+.\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: |
          echo ${{ secrets.KEYSTORE }} | base64 --decode > $HOME/key.jks
          echo ${{ secrets.KEY_PROP }} | base64 --decode > $HOME/key.properties
      - run: flutter build apk --release
      - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/BanGDemo-${{ github.ref_name }}.apk
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.TOKEN }}
